#!/bin/bash

set -e

export AGALMA_DB="/gpfs/data/cdunn/analyses/agalma-siphonophora-20170209.sqlite"

agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-CGATGT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-CGATGT_1.fastq --species "Agalma elegans" --ncbi_id "316166" --itis_id "51383" --extraction_id "FEG0375" --library_id "FEG0375" --library_type "transcriptome" --individual "BW02-agalma-2" --treatment "gastrozooids" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-TTAGGC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-TTAGGC_1.fastq --species "Agalma elegans" --ncbi_id "316166" --itis_id "51383" --extraction_id "FEG0376" --library_id "FEG0376" --library_type "transcriptome" --individual "BW01-60" --treatment "nectophores" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-GCCAAT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-GCCAAT_1.fastq --species "Agalma elegans" --ncbi_id "316166" --itis_id "51383" --extraction_id "FEG0377" --library_id "FEG0377" --library_type "transcriptome" --individual "BW02-agalma-2" --treatment "nectophores" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-CAGATC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-CAGATC_1.fastq --species "Agalma elegans" --ncbi_id "316166" --itis_id "51383" --extraction_id "FEG0378" --library_id "FEG0378" --library_type "transcriptome" --individual "BW02-agalma-3" --treatment "nectophores" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-ACTTGA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-ACTTGA_1.fastq --species "Agalma elegans" --ncbi_id "316166" --itis_id "51383" --extraction_id "FEG0379" --library_id "FEG0379" --library_type "transcriptome" --individual "BW01-60" --treatment "gastrozooids" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-GATCAG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-GATCAG_1.fastq --species "Agalma elegans" --ncbi_id "316166" --itis_id "51383" --extraction_id "FEG0381" --library_id "FEG0381" --library_type "transcriptome" --individual "BW02-agalma-3" --treatment "gastrozooids" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"

agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Agalma_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Agalma_R2.fastq -s 'Agalma elegans' -n '316166' -d '51383' -e 'FEG0371|FEG0372' -l 'FEG0371|FEG0372' -c 'Brown Genomics Core' -t 'NGZ and SGZ' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq RNA Sample Prep Kit RNA Purification Beads ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-73-C0JUVACXX-7-AGALMA2' -v 'BW02-agalma-1'

agalma catalog insert --id "HWI-ST625-49-A81MCVABXX-6-ACAGTG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-49-A81MCVABXX-6-ACAGTG_1.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG294" --library_id "FEG294" --library_type "transcriptome" --individual "D195-D6" --treatment "gastrozooids" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D6, gastrozooids, NEB magnetic, TruSeq" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-49-A81MCVABXX-6-CGATGT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-49-A81MCVABXX-6-CGATGT_1.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG292" --library_id "FEG292" --library_type "transcriptome" --individual "D195-D4" --treatment "nectophores" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D4, nectophores, NEB magnetic, TruSeq" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-49-A81MCVABXX-6-TGACCA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-49-A81MCVABXX-6-TGACCA_1.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG293" --library_id "FEG293" --library_type "transcriptome" --individual "D195-D4" --treatment "gastrozooids" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D4, gastrozooids, NEB magnetic, TruSeq" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-49-A81MCVABXX-7-CAGATC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-49-A81MCVABXX-7-CAGATC_1.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG296" --library_id "FEG296" --library_type "transcriptome" --individual "D198-SS10" --treatment "nectophores" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D6, nectophores, NEB magnetic, TruSeq" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-49-A81MCVABXX-7-CTTGTA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-49-A81MCVABXX-7-CTTGTA_1.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG297" --library_id "FEG297" --library_type "transcriptome" --individual "D198-SS10" --treatment "gastrozooids" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D6, gastrozooids, NEB magnetic, TruSeq" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-49-A81MCVABXX-7-GCCAAT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-49-A81MCVABXX-7-GCCAAT_1.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG295" --library_id "FEG295" --library_type "transcriptome" --individual "D195-D6" --treatment "nectophores" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D6, nectophores, NEB magnetic, TruSeq" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"

agalma catalog insert --id "HWI-ST625-51-C02UNACXX-8-CAGATC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-CAGATC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-CAGATC_2.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG296" --library_id "FEG296" --library_type "transcriptome" --treatment "young nectos #3" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D6, nectophores, Dynabeads, TruSeq" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-51-C02UNACXX-8-CGATGT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-CGATGT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-CGATGT_2.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG292" --library_id "FEG292" --library_type "transcriptome" --treatment "young nectos #1" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D4, nectophores, Dynabeads, TruSeq" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-51-C02UNACXX-8-GCCAAT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-GCCAAT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-GCCAAT_2.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG295" --library_id "FEG295" --library_type "transcriptome" --treatment "young nectos #2" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "D195-D6, nectophores, Dynabeads, TruSeq" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-51-C02UNACXX-8-GGCTAC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-GGCTAC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-GGCTAC_2.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG312" --library_id "FEG312" --library_type "transcriptome" --treatment "SGZ no gastros" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-51-C02UNACXX-8-TAGCTT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-TAGCTT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-8-TAGCTT_2.fastq --species "Bargmannia elongata" --ncbi_id "316231" --itis_id "51386" --extraction_id "FEG311" --library_id "FEG311" --library_type "transcriptome" --treatment "young gastros no yellow" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit" 

agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_R2.fastq -s 'Bargmannia elongata' -n '316231' -d '51386' -e 'FEG311|FEG312|FEG292|FEG295|FEG296' -l 'FEG311|FEG312|FEG292|FEG295|FEG296' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-8-BARGMANNIA'
agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N0_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N0_R2.fastq -s 'Bargmannia elongata' -n '316231' -d '51386' -e 'FEG311|FEG312|FEG292|FEG295|FEG296' -l 'FEG311|FEG312|FEG292|FEG295|FEG296' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-8-BARGMANNIA-N0'
agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N1_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N1_R2.fastq -s 'Bargmannia elongata' -n '316231' -d '51386' -e 'FEG311|FEG312|FEG292|FEG295|FEG296' -l 'FEG311|FEG312|FEG292|FEG295|FEG296' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-8-BARGMANNIA-N1'
agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N2_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N2_R2.fastq -s 'Bargmannia elongata' -n '316231' -d '51386' -e 'FEG311|FEG312|FEG292|FEG295|FEG296' -l 'FEG311|FEG312|FEG292|FEG295|FEG296' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-8-BARGMANNIA-N2'
agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N3_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N3_R2.fastq -s 'Bargmannia elongata' -n '316231' -d '51386' -e 'FEG311|FEG312|FEG292|FEG295|FEG296' -l 'FEG311|FEG312|FEG292|FEG295|FEG296' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-8-BARGMANNIA-N3'
agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N4_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Bargmannia_N4_R2.fastq -s 'Bargmannia elongata' -n '316231' -d '51386' -e 'FEG311|FEG312|FEG292|FEG295|FEG296' -l 'FEG311|FEG312|FEG292|FEG295|FEG296' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-8-BARGMANNIA-N4'

agalma catalog insert --id "EAS1745-19-unknown-1-0" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/EAS1745-19-unknown-1-0_1.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG272" --library_id "FEG272" --library_type "transcriptome" --individual "D102-D7" --treatment "nectophores" --sequencer "Illumina GA IIx" --seq_center "Brown Genomics Core" --note "D102-D7, nectophores, NEB magnetic, NEBNext" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | NEBNext RNA Sample Prep. Master Mix Set 1"
agalma catalog insert --id "EAS1745-19-unknown-2-0" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/EAS1745-19-unknown-2-0_1.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG273" --library_id "FEG273" --library_type "transcriptome" --individual "D102-D7" --treatment "gastrozooids" --sequencer "Illumina GA IIx" --seq_center "Brown Genomics Core" --note "D102-D7, gastrozooids, NEB magnetic, NEBNext" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | NEBNext RNA Sample Prep. Master Mix Set 1"
agalma catalog insert --id "EAS1745-19-unknown-5-0" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/EAS1745-19-unknown-5-0_1.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG274" --library_id "FEG274" --library_type "transcriptome" --individual "D107-D1" --treatment "nectophores" --sequencer "Illumina GA IIx" --seq_center "Brown Genomics Core" --note "D107-D1, nectophores, NEB magnetic, NEBNext" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | NEBNext RNA Sample Prep. Master Mix Set 1"
agalma catalog insert --id "EAS1745-19-unknown-6-0" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/EAS1745-19-unknown-6-0_1.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG275" --library_id "FEG275" --library_type "transcriptome" --individual "D107-D1" --treatment "gastrozooids" --sequencer "Illumina GA IIx" --seq_center "Brown Genomics Core" --note "D107-D1, gastrozooid, NEB magnetic, NEBNext" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | NEBNext RNA Sample Prep. Master Mix Set 1"
agalma catalog insert --id "EAS1745-19-unknown-7-0" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/EAS1745-19-unknown-7-0_1.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG276" --library_id "FEG276" --library_type "transcriptome" --individual "D107-SS6" --treatment "nectophores" --sequencer "Illumina GA IIx" --seq_center "Brown Genomics Core" --note "D107-SS6, nectophores, NEB magnetic, NEBNext" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | NEBNext RNA Sample Prep. Master Mix Set 1"
agalma catalog insert --id "EAS1745-19-unknown-8-0" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/EAS1745-19-unknown-8-0_1.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG277" --library_id "FEG277" --library_type "transcriptome" --individual "D107-SS6" --treatment "gastrozooids" --sequencer "Illumina GA IIx" --seq_center "Brown Genomics Core" --note "D107-SS6, gastrozooids, NEB magnetic, NEBNext" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | NEBNext RNA Sample Prep. Master Mix Set 1"

agalma catalog insert --id "HWI-ST625-51-C02UNACXX-6-ATCACG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-6-ATCACG_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-6-ATCACG_2.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG309" --library_id "FEG309" --library_type "transcriptome" --treatment "nectophores" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "combo with extractions FEG287/309" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-51-C02UNACXX-6-CGATGT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-6-CGATGT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-6-CGATGT_2.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG291" --library_id "FEG291" --library_type "transcriptome" --treatment "SGZ" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-51-C02UNACXX-6-TGACCA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-6-TGACCA_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-6-TGACCA_2.fastq --species "Frillagalma vityazi" --itis_id "719183" --extraction_id "FEG286" --library_id "FEG286" --library_type "transcriptome" --treatment "cormidium" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"

agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Frillagalma_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Frillagalma_R2.fastq -s 'Frillagalma vityazi' -d '719183' -e 'FEG291|FEG286|FEG309' -l 'FEG291|FEG286|FEG309' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-6-FRILLAGALMA'

agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-TGACCA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-TGACCA_1.fastq --species "Nanomia bijuga" --ncbi_id "168759" --itis_id "51389" --extraction_id "FEG0380" --library_id "FEG0380" --library_type "transcriptome" --individual "D331-SS5a" --treatment "palpons" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-ATCACG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-ATCACG_1.fastq --species "Nanomia bijuga" --ncbi_id "168759" --itis_id "51389" --extraction_id "FEG0374" --library_id "FEG0374" --library_type "transcriptome" --individual "D326-SS1" --treatment "palpons" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-75-D0PBDACXX-6-ACAGTG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-75-D0PBDACXX-6-ACAGTG_1.fastq --species "Nanomia bijuga" --ncbi_id "168759" --itis_id "51389" --extraction_id "FEG0382" --library_id "FEG0382" --library_type "transcriptome" --individual "D331-SS5b" --treatment "palpons" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/100603_EAS1745_0004/Data/Intensities/BaseCalls/SS42_L001_R1_001.fastq.gz -s 'Nanomia bijuga' -n '168759' -d '51389' -e 'SS42' -l 'SS42' -c 'Brown Genomics Core' -t 'nectophores' -q 'Illumina GA IIx' --note '' -b 'transcriptome' --sample_prep 'NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina mRNA-Seq Sample Prep. Kit' -v 'D104-SS7'
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/100603_EAS1745_0004/Data/Intensities/BaseCalls/SS43_L002_R1_001.fastq.gz -s 'Nanomia bijuga' -n '168759' -d '51389' -e 'SS43' -l 'SS43' -c 'Brown Genomics Core' -t 'gastrozooids' -q 'Illumina GA IIx' --note '' -b 'transcriptome' --sample_prep 'NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina mRNA-Seq Sample Prep. Kit' -v 'D104-SS7'
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/100603_EAS1745_0004/Data/Intensities/BaseCalls/SS48_L003_R1_001.fastq.gz -s 'Nanomia bijuga' -n '168759' -d '51389' -e 'SS48' -l 'SS48' -c 'Brown Genomics Core' -t 'nectophores' -q 'Illumina GA IIx' --note '' -b 'transcriptome' --sample_prep 'NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina mRNA-Seq Sample Prep. Kit' -v 'D107-SS8#1'
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/100603_EAS1745_0004/Data/Intensities/BaseCalls/SS49_L006_R1_001.fastq.gz -s 'Nanomia bijuga' -n '168759' -d '51389' -e 'SS49' -l 'SS49' -c 'Brown Genomics Core' -t 'gastrozooids' -q 'Illumina GA IIx' --note '' -b 'transcriptome' --sample_prep 'NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina mRNA-Seq Sample Prep. Kit' -v 'D107-SS8#1'
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/100603_EAS1745_0004/Data/Intensities/BaseCalls/SS50_L007_R1_001.fastq.gz -s 'Nanomia bijuga' -n '168759' -d '51389' -e 'SS50' -l 'SS50' -c 'Brown Genomics Core' -t 'nectophores' -q 'Illumina GA IIx' --note '' -b 'transcriptome' --sample_prep 'NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina mRNA-Seq Sample Prep. Kit' -v 'D105-SS6'
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/100603_EAS1745_0004/Data/Intensities/BaseCalls/SS51_L008_R1_001.fastq.gz -s 'Nanomia bijuga' -n '168759' -d '51389' -e 'SS51' -l 'SS51' -c 'Brown Genomics Core' -t 'gastrozooids' -q 'Illumina GA IIx' --note '' -b 'transcriptome' --sample_prep 'NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina mRNA-Seq Sample Prep. Kit' -v 'D105-SS6'

agalma catalog insert --id "HWI-ST625-51-C02UNACXX-7-ACTTGA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-7-ACTTGA_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-7-ACTTGA_2.fastq --species "Nanomia bijuga" --ncbi_id "168759" --itis_id "51389" --extraction_id "FEG284" --library_id "FEG284" --library_type "transcriptome" --treatment "siphosome w/ young gonos" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-51-C02UNACXX-7-TTAGGC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-7-TTAGGC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-51-C02UNACXX-7-TTAGGC_2.fastq --species "Nanomia bijuga" --ncbi_id "168759" --itis_id "51389" --extraction_id "FEG298" --library_id "FEG298" --library_type "transcriptome" --treatment "NGZ+SGZ" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "NEB Magnetic mRNA Isolation Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"

agalma catalog insert -p /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Nanomia_R1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/concatenated/Nanomia_R2.fastq -s 'Nanomia bijuga' -n '168759' -d '51389' -e 'FEG298|FEG284|FEG283' -l 'FEG298|FEG284|FEG283' -c 'Brown Genomics Core' -t 'mix' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'mix, see individual sample numbers | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-51-C02UNACXX-7-NANOMIA'

agalma catalog insert -p /gpfs/home/cdunn/data/illumina/Project_Freya_Goetz_lane57_120302_SN625_0073_AC0JUVACXX/FEG0369_TTAGGC_L007_R1_001.fastq.gz /gpfs/home/cdunn/data/illumina/Project_Freya_Goetz_lane57_120302_SN625_0073_AC0JUVACXX/FEG0369_TTAGGC_L007_R2_001.fastq.gz -s 'Physalia physalis' -n '168775' -d '719181' -e 'FEG0369' -l 'FEG0369' -c 'Brown Genomics Core' -t 'whole animal w/o most of float' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq RNA Sample Prep Kit RNA Purification Beads ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit'



agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/111012_SN625_0054_BC026EACXX-Freya-Goetz-filtered-new/FEG-339_ATCACG_L006_R1_001.fastq.gz /gpfs/data/cdunn/sequences/illumina/111012_SN625_0054_BC026EACXX-Freya-Goetz-filtered-new/FEG-339_ATCACG_L006_R2_001.fastq.gz -s 'Abylopsis tetragona' -n '316209' -d '51370' -e 'FEG339' -l 'FEG339' -c 'Brown Genomics Core' -q 'Illumina HiSeq 2000' -b 'transcriptome' --sample_prep 'Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-54-C026EACXX-6-ATCACG'
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/111012_SN625_0054_BC026EACXX-Freya-Goetz-filtered-new/Acit_TATC_L003_R1_001.fastq.gz /gpfs/data/cdunn/sequences/illumina/111012_SN625_0054_BC026EACXX-Freya-Goetz-filtered-new/Acit_TATC_L003_R2_001.fastq.gz -s 'Aegina citrea' -n '168710' -d '51148' -e 'Acit' -l 'Acit' -c 'Brown Genomics Core' -t 'whole animal' -q 'Illumina HiSeq 2000' --note '' -b 'transcriptome' --sample_prep 'from Haddock lab | NuGEN Encore' --id 'HWI-ST625-54-C026EACXX-3-TATC'
agalma catalog insert --id "SRX231866" --paths /gpfs/data/cdunn/sequences/public/SRA/Aiptasia_pallida/SRX231866_1.fastq.gz /gpfs/data/cdunn/sequences/public/SRA/Aiptasia_pallida/SRX231866_2.fastq.gz --species "Aiptasia pallida" --ncbi_id "12923" --itis_id "52770" --library_type "transcriptome" --sequencer "Illumina PE" --note "Downloaded 3 runs from SRA, Accession SRX231866" --sample_prep " | "
agalma catalog insert -p /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Alatina/Alatina_R1.fq.gz /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Alatina/Alatina_R2.fq.gz -s 'Alatina alata' -n '1193083' -d '51451' -e '' -l '' -c '' -t '' -q 'Illumina HiSeq' --note 'ITIS ID for family Carybdeidae. This is a combination of 3 libraries: R3 (mature adult pedalium and tentacle); R54 (blastulae); and R56 (planulae)' -b 'transcriptome' --sample_prep ' | ' --id 'HISEQ-168-C3DEYACXX-8-ALATINA'
agalma catalog insert --id "HWI-ST625-54-C026EACXX-6-TTAGGC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-TTAGGC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-TTAGGC_2.fastq --species "Apolemia rubriversa" --itis_id "51421" --extraction_id "FEG355" --library_id "FEG355" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round & Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-61-C02G3ACxx-6-GGCTAC" --paths /gpfs/data/cdunn/sequences/processed/Atolla_12May2012/Atolla.pairs.1.fastq.gz /gpfs/data/cdunn/sequences/processed/Atolla_12May2012/Atolla.pairs.2.fastq.gz --species "Atolla vanhoeffeni" --ncbi_id "86043" --itis_id "51562" --extraction_id "Atolla" --library_id "Atolla" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "readPairs with 454 adapters removed with trimReads" --sample_prep "from Nathan Shaner | Shaner 454 | NEB Fragmentase | Illumina TruSeq RNA Sample Prep Kit (from end repair on)"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-6-ACAGTG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-ACAGTG_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-ACAGTG_2.fastq --species "Chelophyes appendiculata" --ncbi_id "316211" --itis_id "51272" --extraction_id "FEG351" --library_id "FEG351" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 1 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-6-GCCAAT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-GCCAAT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-GCCAAT_2.fastq --species "Chuniphyes multidentata" --ncbi_id "316200" --itis_id "51304" --extraction_id "FEG325" --library_id "FEG325" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert -p /gpfs/data/cdunn/sequences/public/dbEST/Clytia_hemisphaerica/postcluster/processed.nc.fasta -s 'Clytia hemisphaerica' -n '252671' -d '49583' -e '' -l '' -c '' -t '' -q '' --note 'Assembled EST from Cnidaria Tree of Life' -b 'transcriptome' --sample_prep ' | ' --id 'dbEST_CLYHEM'
agalma catalog insert --id "HWI-ST625-54-C026EACXX-6-CAGATC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-CAGATC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-6-CAGATC_2.fastq --species "Cordagalma sp" --itis_id "51393" --extraction_id "FEG328" --library_id "FEG328" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --paths /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Ectopleura_larynx/Ectopleura_R1.chast.fastq.gz /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Ectopleura_larynx/Ectopleura_R2.chast.fastq.gz -s 'Ectopleura larynx' -n '264052' -d '719103' -e '' -l '' -c '' --id 'HWI-ST420-69-D0F2NACXX-3-ECTOPLEURA' -t '' -q 'Illumina HiSeq' --note 'Data generated in the lab of Paulyn Cartwright (Kansas)' -b 'transcriptome' --sample_prep ' | '
agalma catalog insert --id "HWI-ST625-54-C026EACXX-7-TAGCTT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-TAGCTT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-TAGCTT_2.fastq --species "Erenna richardi" --itis_id "51396" --extraction_id "FEG356" --library_id "FEG356" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-7-GGCTAC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-GGCTAC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-GGCTAC_2.fastq --species "Forskalia asymmetrica" --ncbi_id "316178" --itis_id "51417" --extraction_id "FEG357" --library_id "FEG357" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-8-ATCACG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-ATCACG_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-ATCACG_2.fastq --species "Hippopodius hippopus" --ncbi_id "168745" --itis_id "51331" --extraction_id "FEG337" --library_id "FEG337" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert -p /gpfs/data/cdunn/sequences/public/ncbi/Hydra_magnipapillata/rna.fa -s 'Hydra magnipapillata' -n '6085' -d '50845' -e '' -l '' -c '' -t '' -q '' --note 'Gene predictions from genome sequencing' -b 'genome' --sample_prep ' | ' --id 'NCBI_HYDMAG'
agalma catalog insert -p /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Hydractinia_symbiolongicarpus/Hydractinia_R1.fq.gz /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Hydractinia_symbiolongicarpus/Hydractinia_R2.fq.gz -s 'Hydractinia symbiolongicarpus' -n '13093' -d '719085' -e '' -l '' -c '' -t '' -q 'Illumina HiSeq' --note 'Data generated in the lab of Paulyn Cartwright (Kansas)' -b 'transcriptome' --sample_prep ' | ' --id 'HISEQ-129-C25BFACXX-8-HYDRACTINIA'
agalma catalog insert --id "HWI-ST625-73-C0JUVACXX-7-ATCACG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-73-C0JUVACXX-7-ATCACG_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-73-C0JUVACXX-7-ATCACG_2.fastq --species "Kephyes ovata" --ncbi_id "645392" --itis_id "718958" --extraction_id "FEG0367" --library_id "FEG0367" --library_type "transcriptome" --treatment "siphosome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Illumina TruSeq RNA Sample Prep Kit RNA Purification Beads ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-7-CGATGT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-CGATGT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-CGATGT_2.fastq --species "Lilyopsis fluoracantha" --ncbi_id "326734" --itis_id "51350" --extraction_id "FEG344" --library_id "FEG344" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 1 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-8-TTAGGC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-TTAGGC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-TTAGGC_2.fastq --species "Lychnagalma utricularia" --ncbi_id "338248" --itis_id "719187" --extraction_id "FEG358" --library_id "FEG358" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round & Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-7-TGACCA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-TGACCA_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-TGACCA_2.fastq --species "Marrus claudanielis" --ncbi_id "338246" --itis_id "51390" --extraction_id "FEG359" --library_id "FEG359" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert -p /gpfs/data/cdunn/sequences/public/JGI_August2012/Nematostella_vectensis/Nemve_No_ribosomes_FilteredModels_NO_TABS.fas -s 'Nematostella vectensis' -n '45351' -d '52498' -e '' -l '' -c '' -t '' -q '' --note 'Filtered transcript predictions from JGI used in Nematostella paper (Rebecca et al).  See paper for details' -b 'genome' --sample_prep ' | ' --id 'JGI_NEMVEC'
agalma catalog insert --id "HWI-ST625-54-C026EACXX-8-ACAGTG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-ACAGTG_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-ACAGTG_2.fastq --species "Physonect sp " --itis_id "718936" --extraction_id "FEG348" --library_id "FEG348" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 1 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HISEQ-134-C27MTACXX-2-PODOCORYNA" --paths /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Podocoryna/Podocoryna_R1.fq.gz /gpfs/data/cdunn/sequences/collaborators/cnidaria_paulyn/Podocoryna/Podocoryna_R2.fq.gz -s 'Podocoryna carnea' -n '6096' -d '719298' -e '' -l '' -c '' -t '' -q 'Illumina HiSeq' --note "Combined Med1 and RP135 libraries from Paulyn's lab.  Med1 is medusa and RP135 is polyp with medusae buds at some developmental stage." -b 'transcriptome' --sample_prep ' | '
agalma catalog insert --id "HWI-ST625-54-C026EACXX-7-GATCAG" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-GATCAG_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-7-GATCAG_2.fastq --species "Prayidae D27SS7" --itis_id "51332" --extraction_id "FEG329" --library_id "FEG329" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --note "undescribed species" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert -p /gpfs/data/cdunn/sequences/illumina/111012_SN625_0054_BC026EACXX-Freya-Goetz-filtered-new/FEG-354_CTTGTA_L007_R1_001.fastq.gz /gpfs/data/cdunn/sequences/illumina/111012_SN625_0054_BC026EACXX-Freya-Goetz-filtered-new/FEG-354_CTTGTA_L007_R2_001.fastq.gz -s 'Prayidae D27D2' -d '51332' -e 'FEG354' -l 'FEG354' -c 'Brown Genomics Core' -t '' -q 'Illumina HiSeq 2000' --note 'Original ID was Rosacea, but photos look like Craseoa' -b 'transcriptome' --sample_prep 'Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit' --id 'HWI-ST625-54-C026EACXX-7-CTTGTA'
agalma catalog insert --id "HWI-ST625-54-C026EACXX-8-GCCAAT" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-GCCAAT_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-GCCAAT_2.fastq --species "Resomia ornicephala" --ncbi_id "557396" --itis_id "718936" --extraction_id "FEG341" --library_id "FEG341" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-8-CAGATC" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-CAGATC_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-CAGATC_2.fastq --species "Rhizophysa filiformis" --ncbi_id "316187" --itis_id "51433" --extraction_id "FEG322" --library_id "FEG322" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Invitrogen Dynabeads mRNA DIRECT kit ; 1 round | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert --id "HWI-ST625-54-C026EACXX-8-ACTTGA" --paths /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-ACTTGA_1.fastq /gpfs/data/cdunn/sequences/sra/siphonophora/filtered/HWI-ST625-54-C026EACXX-8-ACTTGA_2.fastq --species "Stephalia dilata" --ncbi_id "316222" --itis_id "51414" --extraction_id "FEG350" --library_id "FEG350" --library_type "transcriptome" --sequencer "Illumina HiSeq 2000" --seq_center "Brown Genomics Core" --sample_prep "Trizol | Invitrogen Dynabeads mRNA Purification Kit ; 2 rounds | Illumina TruSeq RNA Sample Prep Kit"
agalma catalog insert -p /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0027_CGATGT_L005_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0027_CGATGT_L005_R2_001.fastq.gz -s 'Diphyes dispar' -n '316177' -d '51307' -e 'CMN0027' -l 'CMN0027' -c 'Brown' -t 'SGZ and mature gastrozooid with stem' -q 'Illumina HiSeq 2500' --note 'Extraction ID: CM27' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0036_CCGTCC_L005_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0036_CCGTCC_L005_R2_001.fastq.gz -s 'Apolemia lanosa' -n '1390099' -e 'CMN0036' -l 'CMN0036' -c 'Brown' -t 'NGZ, SGZ, post SGZ' -q 'Illumina HiSeq 2500' --note 'Extraction ID: CM43' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0034_AGTTCC_L005_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0034_AGTTCC_L005_R2_001.fastq.gz -s 'Apolemia sp'  -d '51421' -e 'CMN0034' -l 'CMN0034' -c 'Brown' -t 'stem' -q 'Illumina HiSeq 2500' --note 'Extraction ID: CM41' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0037_GTCCGC_L005_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0037_GTCCGC_L005_R2_001.fastq.gz -s 'Bargmannia amoena' -n '316197' -d '719188' -e 'CMN0037' -l 'CMN0037' -c 'Brown' -t 'SGZ and stem' -q 'Illumina HiSeq 2500' --note 'Extraction ID: CM44' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0028_TGACCA_L005_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CMN0027_CMN0038_Cat_Munro/CMN0028_TGACCA_L005_R2_001.fastq.gz -s 'Bargmannia lata' -d '719189' -e 'CMN0028' -l 'CMN0028' -c 'Brown' -t 'Mature gastrozooid with stem, and NGZ' -q 'Illumina HiSeq 2500' --note 'Extraction ID: CM28' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0089_ATCACG_L002_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0089_ATCACG_L002_R2_001.fastq.gz -s 'Rudjakovia sp' -e 'CMN0089' -l 'CMN0089' -c 'Brown Genomics Core' -t 'piece of stem' -q 'Ilumina HiSeq' --note 'D494-D8 Rudjakovia #19, original ID CM91' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded mRNA'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0090_ACTTGA_L002_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0090_ACTTGA_L002_R2_001.fastq.gz -s 'Thermopalia sp' -e 'CMN0090' -l 'CMN0090' -c 'Brown Genomics Core' -t 'siphosome' -q 'Ilumina HiSeq' --note 'extraction ID CM92' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded mRNA'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0091_TAGCTT_L002_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0091_TAGCTT_L002_R2_001.fastq.gz -s 'Physophora gilmeri' -e 'CMN0091' -l 'CMN0091' -c 'Brown Genomics Core' -t 'nectosomal and siphosomal growth zone' -q 'Ilumina HiSeq' --note 'extraction ID CM93' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded mRNA'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0092_GGCTAC_L002_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0092_GGCTAC_L002_R2_001.fastq.gz -s 'Halistemma rubrum' -n '316183' -d '51400' -e 'CMN0092' -l 'CMN0092' -c 'Brown Genomics Core' -t 'nectosomal and siphosomal growth zone' -q 'Ilumina HiSeq' --note 'extraction ID CM94' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded mRNA'
agalma catalog insert -p /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0093_CTTGTA_L002_R1_001.fastq.gz /gpfs/data/cdunn/illumina/CNM0081_CNM0093_Cat_Munro/CNM0093_CTTGTA_L002_R2_001.fastq.gz -s 'Athorybia rosacea' -n '316173' -d '51428' -e 'CMN0093' -l 'CMN0093' -c 'Brown Genomics Core' -t 'whole' -q 'Ilumina HiSeq' --note 'extraction ID CM97' -b 'transcriptome' --sample_prep 'Trizol | Illumina TruSeq Stranded mRNA'